force-app/main/default/objects/LogPlatformEventsServiceTestEvent__e/LogPlatformEventsServiceTestEvent__e.object-meta.xml
<CustomObject>
    <description>Event used in test class for LogPlatformEventsService. This is not essential for deploying this service, you can alter the LogPlatformEventsServiceTest class to use an event(s) that will exist in your environments.

Bear in mind that there are maximum Platform Event Definition limits for all environments which are documented here: https://developer.salesforce.com/docs/atlas.en-us.platform_events.meta/platform_events/platform_event_limits.htm</description>
    <label>LogPlatformEventsServiceTestEvent</label>
    <pluralLabel>LogPlatformEventsServiceTestEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogPlatformEventsServiceTestEvent__e/fields/JsonTextField__c.field-meta.xml
<CustomField>
    <fullName>JsonTextField__c</fullName>
    <description>Text field that stores JSON string, which can be parsed and evaluated for specific internal values and logged like all other fields on the Platform Event.</description>
    <label>JsonTextField</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log__c/Platform_Event_Log__c.object-meta.xml
<CustomObject>
    <description>A log of all platform events consumed while trigger for that type is enabled.</description>
    <label>Platform Event Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log__c/fields/Publishing_User__c.field-meta.xml
<CustomField>
    <fullName>Publishing_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who published the Platform Event. Is populated by CreatedById by default, but can configure a populating field in the custom metadata configuration.</description>
    <inlineHelpText>User who published the Platform Event. Is populated by CreatedById by default, but can configure a populating field in the custom metadata configuration.</inlineHelpText>
    <label>Publishing User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Platform_Event_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/Platform_Event_Log_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Manage the configuration for Platform Event Logging Service for multiple Platform Event types.</description>
    <label>Platform Event Log Configuration</label>
    <pluralLabel>Platorm Event Log Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Enable_Debug__c.field-meta.xml
<CustomField>
    <fullName>Enable_Debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Provide debugging in the Apex logs.</description>
    <inlineHelpText>Provide debugging in the Apex logs.</inlineHelpText>
    <label>Enable Debug</label>
    <type>Checkbox</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Enable_Log_Records__c.field-meta.xml
<CustomField>
    <fullName>Enable_Log_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable or disabled the generation of Platform Event Log records.</description>
    <inlineHelpText>Enable or disabled the generation of Platform Event Log records.</inlineHelpText>
    <label>Enable Log Records</label>
    <type>Checkbox</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Field_Logs__c.field-meta.xml
<CustomField>
    <fullName>Field_Logs__c</fullName>
    <description>Comma separated list of Platform Event Field API names to be logged in Platform Event Field Log object on parent Platform Event Log record</description>
    <inlineHelpText>Comma separated list of Platform Event Field API names to be logged in Platform Event Field Log object on parent Platform Event Log record</inlineHelpText>
    <label>Field Logs</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Completely enable or disable the Platform Event Logging Service for this Platform Event Type</description>
    <inlineHelpText>Completely enable or disable the Platform Event Logging Service for this Platform Event Type</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Platform_Event_Type_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Type_API_Name__c</fullName>
    <description>API Name of Platform Event Type</description>
    <inlineHelpText>API Name of Platform Event Type</inlineHelpText>
    <label>Platform Event Type API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Publishing_User_Field__c.field-meta.xml
<CustomField>
    <fullName>Publishing_User_Field__c</fullName>
    <description>Field path used to pull user id to set as the Platform_Event_Log__c.Publishing_User__c field. Defaults to CreatedById if not populated.</description>
    <inlineHelpText>Field path used to pull user id to set as the Platform_Event_Log__c.Publishing_User__c field. Defaults to CreatedById if not populated.</inlineHelpText>
    <label>Publishing User Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/Platform_Event_Log_Field__c.object-meta.xml
<CustomObject>
    <description>Individual field values for a platform event log for easier readability and reporting</description>
    <label>Platform Event Log Field</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Log Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>Name of the field being captured</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the field being captured</inlineHelpText>
    <label>Field Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <description>Value of the Platform Event Field</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value of the Platform Event Field</inlineHelpText>
    <label>Field Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Platform_Event_Log__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Log__c</fullName>
    <label>Platform Event Log</label>
    <referenceTo>Platform_Event_Log__c</referenceTo>
    <relationshipLabel>Platform Event Log Fields</relationshipLabel>
    <relationshipName>Platform_Event_Log_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LogPlatformEventsServiceTest.cls
@isTest
global class LogPlatformEventsServiceTest 
{
    private static final integer count=500;
    private static list<LogPlatformEventsServiceTestEvent__e> testEvents;
    private static list<Platform_Event_Log_Configuration__mdt> eventConfigurations;
    private static final string jsonFieldString;
    private static final string invalidJsonString;

    static 
    {
        eventConfigurations = new List<Platform_Event_Log_Configuration__mdt>();
        jsonFieldString = '{"Publishing_User__c":"0051N000006Ckw6QAC","innerFieldOne":"innerValueOne","innerFieldTwo":"innerValueTwo","innerFieldThree":{"deepInnerFieldOne":"deepInnerValueOne"}}';
        invalidJsonString = '{\"realfield\":\"realValue\":errorField\":\"errorValue\"}'; // throw error in JSON.deserialize
    }


    /* 
    * Leveraging the JSON.deserialize() method allows us to work 
    * around "Field Not Writable" limitations for mock data
    */

    private static void createPlatformEventList()
    {
        testEvents = new list<LogPlatformEventsServiceTestEvent__e>();
        for (integer i=0;i<count;i++)
        {
            testEvents.add((LogPlatformEventsServiceTestEvent__e)JSON.deserialize('{' +
            '"ReplayId":"123456'+i+'",' +
            '"JsonTextField__c":' + JSON.serialize(jsonFieldString)  +
            '}',
             LogPlatformEventsServiceTestEvent__e.class));
        }
    }

    private static void createPlatformEventListWithInvalidJson()
    {
        testEvents = new list<LogPlatformEventsServiceTestEvent__e>();
        for (integer i=0;i<count;i++)
        {
            LogPlatformEventsServiceTestEvent__e e = (LogPlatformEventsServiceTestEvent__e)JSON.deserialize('{' +
            '"ReplayId":"123456'+i+'"' +
            '}',
            LogPlatformEventsServiceTestEvent__e.class);
            e.JsonTextField__c = invalidJsonString;

            testEvents.add(e);
        }
    }

    private static void createPlatformEventConfigurationRecords(integer count, string eventType, string fieldsList)
    {
        for (integer i=0;i<count;i++) 
        {
            eventConfigurations.add((Platform_Event_Log_Configuration__mdt)JSON.deserialize('{' +
                '"ReplayId":"0123456'+i+'",' +
                '"DeveloperName":"EVENT LOG CONFIG '+i+'",' +
                '"MasterLabel":"EVENT LOG CONFIG '+i+'",' +
                '"Is_Active__c":true,' +
                '"Enable_Debug__c":true,' +
                '"Enable_Log_Records__c":true,' +
                '"Publishing_User_Field__c":"JsonTextField__c.Publishing_User__c",' +
                '"Field_Logs__c":"'+fieldsList+'",' +
                '"Platform_Event_Type_API_Name__c":"'+eventType+'"' +
                '}',
                Platform_Event_Log_Configuration__mdt.class));
        }
    }    

    global static list<Platform_Event_Log_Configuration__mdt> getEventConfigurations()
    {
        return eventConfigurations;
    }

    
    // ALL TEST METHODS BELOW

    @isTest
    static void passEmptyListToConstructor() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(new List<LogPlatformEventsServiceTestEvent__e>());
            eventlogger.logEvents();
        } catch (exception e) {
            emptyListException = e;
        }
        test.stopTest();

        System.assert(emptyListException!=null);
        System.assert(emptyListException.getMessage().contains(LogPlatformEventsService.EMPTY_EVENT_LIST_MESSAGE.split(':')[0]));
    }

    @isTest
    static void passNullToConstructor() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(null);
            eventlogger.logEvents();
        } catch (exception e) {
            emptyListException = e;
        }
        test.stopTest();

        System.assert(emptyListException!=null);
        System.assert(emptyListException.getMessage().contains(LogPlatformEventsService.EMPTY_EVENT_LIST_MESSAGE.split(':')[0]));
    }

    @isTest
    static void noConfigurations() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        createPlatformEventList();

        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(testEvents);
            eventlogger.logEvents();
        } catch (exception e) {
            emptyListException = e;
        }
        test.stopTest();

        System.assert(emptyListException!=null);
        System.assert(emptyListException.getMessage().contains(LogPlatformEventsService.NO_EVENT_CONFIGURATIONS_MESSAGE.split(':')[0]));
    }

    @isTest
    static void multipleActiveConfigurations() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        createPlatformEventList();
        createPlatformEventConfigurationRecords(3,'LogPlatformEventsServiceTestEvent__e','JsonTextField__c');

        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(testEvents);
            eventlogger.logEvents();
        } catch (exception e) {
            emptyListException = e;
        }
        test.stopTest();

        System.assert(emptyListException!=null);
        System.assert(emptyListException.getMessage().contains(LogPlatformEventsService.DUPLICATE_EVENT_CONFIGURATIONS_MESSAGE.split(':')[0]));
    }

    @isTest
    static void activeAndInactiveConfigurationsPassing() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        createPlatformEventList();
        createPlatformEventConfigurationRecords(3,'LogPlatformEventsServiceTestEvent__e','JsonTextField__c');
        eventConfigurations[0].is_active__c=false;
        eventConfigurations[2].is_active__c=false;

        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(testEvents);
            eventlogger.logEvents();
        } catch (exception e) {
            emptyListException = e;
        }
        test.stopTest();

        List<platform_event_log__c> eventLogs = [select id, name from platform_event_log__c];
        System.assert(emptyListException==null);
        System.assertEquals(count, eventLogs.size());
    }

    @isTest
    static void activeAndInactiveConfigurationsFailing() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        createPlatformEventList();
        createPlatformEventConfigurationRecords(3,'LogPlatformEventsServiceTestEvent__e','JsonTextField__c');
        eventConfigurations[0].is_active__c=false;

        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(testEvents);
            eventlogger.logEvents();
        } catch (exception e) {
            emptyListException = e;
        }
        test.stopTest();

        System.assert(emptyListException!=null);
        System.assert(emptyListException.getMessage().contains(LogPlatformEventsService.DUPLICATE_EVENT_CONFIGURATIONS_MESSAGE.split(':')[0]));
    }

    @isTest
    static void oneValidConfiguration() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        createPlatformEventList();
        createPlatformEventConfigurationRecords(1,'LogPlatformEventsServiceTestEvent__e','JsonTextField__c,JsonTextField__c.innerFieldOne,JsonTextField__c.innerFieldThree.deepInnerFieldOne');

        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(testEvents);
            eventlogger.logEvents();
        } catch (exception e) {
            System.debug(e);
            System.debug(e.getStackTraceString());
            emptyListException = e;
        }
        test.stopTest();

        List<platform_event_log__c> eventLogs = [select id, name, publishing_user__c from platform_event_log__c];
        list<platform_event_log_field__c> eventLogFields = [select id, field_name__c, field_value__c from platform_event_log_field__c];

        integer jsonTextFields = 0;
        integer innerFieldOneFields = 0;
        integer deepInnerFieldOneFields = 0;

        for (platform_event_log_field__c eventLogField : eventLogFields)
        {
            System.debug(eventLogField);
            if (eventLogField.field_name__c=='JsonTextField__c' && eventLogField.field_value__c==jsonFieldString)
                jsonTextFields+=1;
            else if (eventLogField.field_name__c=='JsonTextField__c.innerFieldOne' && eventLogField.field_value__c=='innerValueOne')
                innerFieldOneFields+=1;
            else if (eventLogField.field_name__c=='JsonTextField__c.innerFieldThree.deepInnerFieldOne' && eventLogField.field_value__c=='deepInnerValueOne')
                deepInnerFieldOneFields+=1;
        }
        
        System.assert(emptyListException==null);
        System.assertEquals(count, eventLogs.size());
        System.assertEquals(count*3, eventLogFields.size());
        System.assertEquals(count,deepInnerFieldOneFields);
        System.assertEquals(count,innerFieldOneFields);
        System.assertEquals(count,jsonTextFields);

        for (platform_event_log__c log : eventLogs)
        {
            System.assertEquals('0051N000006Ckw6QAC',log.publishing_user__c);
        }
    }

    @isTest
    static void invalidPublishingUserValue() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        createPlatformEventList();
        createPlatformEventConfigurationRecords(1,'LogPlatformEventsServiceTestEvent__e','JsonTextField__c,JsonTextField__c.innerFieldOne,JsonTextField__c.innerFieldThree.deepInnerFieldOne');

        eventConfigurations[0].Publishing_User_Field__c = 'NotAField__c';

        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(testEvents);
            eventlogger.logEvents();
        } catch (exception e) {
            System.debug(e);
            System.debug(e.getStackTraceString());
            emptyListException = e;
        }
        test.stopTest();

        List<platform_event_log__c> eventLogs = [select id, name, publishing_user__c from platform_event_log__c];
        
        
        System.assert(emptyListException==null);
        System.assertEquals(count, eventLogs.size());

        for (platform_event_log__c log : eventLogs)
        {
            System.assertEquals(null,log.publishing_user__c);
        }
    }

    @isTest
    static void erroneousFieldConfiguration() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        createPlatformEventList();
        createPlatformEventConfigurationRecords(1,'LogPlatformEventsServiceTestEvent__e','WrongField__c,JsonTextField__c.OtherWrongField__c.OtherWrongField__c');

        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(testEvents);
            eventlogger.logEvents();
        } catch (exception e) {
            System.debug(e);
            emptyListException = e;
        }
        test.stopTest();

        List<platform_event_log__c> eventLogs = [select id, name from platform_event_log__c];
        System.assert(emptyListException==null);
        System.assertEquals(count, eventLogs.size());
    }

    @isTest
    static void erroneousJsonInPayload() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        createPlatformEventListWithInvalidJSON();
        createPlatformEventConfigurationRecords(1,'LogPlatformEventsServiceTestEvent__e','JsonTextField__c.ErrorField__c');

        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(testEvents);
            eventlogger.logEvents();
        } catch (exception e) {
            System.debug(e);
            emptyListException = e;
        }
        test.stopTest();

        List<platform_event_log__c> eventLogs = [select id, name from platform_event_log__c];
        List<platform_event_log_field__c> eventLogFields = [select id, field_name__c, field_value__c from platform_event_log_field__c];

        System.assert(emptyListException==null);
        System.assertEquals(count, eventLogs.size());
        System.assertEquals(count, eventLogFields.size());

        for (platform_event_log_field__c eventLogField : eventLogFields) 
        {
            System.assertEquals('JsonTextField__c.ErrorField__c',eventLogField.field_name__c);
            System.assert(eventLogField.field_value__c.contains(LogPlatformEventsService.JSON_PARSE_ERROR_MESSAGE.split(':')[0]));
        }
    }

    @isTest
    static void inactiveConfiguration() 
    {
        exception emptyListException;
        LogPlatformEventsService eventlogger;

        createPlatformEventList();
        createPlatformEventConfigurationRecords(1,'LogPlatformEventsServiceTestEvent__e','JsonTextField__c');
        eventConfigurations[0].Is_Active__c = false;
        test.startTest();
        try {
            eventlogger = new LogPlatformEventsService(testEvents);
            eventlogger.logEvents();
        } catch (exception e) {
            System.debug(e);
            System.debug(e.getStackTraceString());
            emptyListException = e;
        }
        test.stopTest();

        List<platform_event_log__c> eventLogs = [select id, name from platform_event_log__c];
        System.assert(emptyListException==null);
        System.assertEquals(0, eventLogs.size());
    }
}