force-app/main/default/objects/LogPlatformEventsServiceTestEvent__e/LogPlatformEventsServiceTestEvent__e.object-meta.xml
<CustomObject>
    <description>Event used in test class for LogPlatformEventsService. This is not essential for deploying this service, you can alter the LogPlatformEventsServiceTest class to use an event(s) that will exist in your environments.

Bear in mind that there are maximum Platform Event Definition limits for all environments which are documented here: https://developer.salesforce.com/docs/atlas.en-us.platform_events.meta/platform_events/platform_event_limits.htm</description>
    <label>LogPlatformEventsServiceTestEvent</label>
    <pluralLabel>LogPlatformEventsServiceTestEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogPlatformEventsServiceTestEvent__e/fields/JsonTextField__c.field-meta.xml
<CustomField>
    <fullName>JsonTextField__c</fullName>
    <description>Text field that stores JSON string, which can be parsed and evaluated for specific internal values and logged like all other fields on the Platform Event.</description>
    <label>JsonTextField</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/Platform_Event_Log_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Manage the configuration for Platform Event Logging Service for multiple Platform Event types.</description>
    <label>Platform Event Log Configuration</label>
    <pluralLabel>Platorm Event Log Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Enable_Debug__c.field-meta.xml
<CustomField>
    <fullName>Enable_Debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Provide debugging in the Apex logs.</description>
    <inlineHelpText>Provide debugging in the Apex logs.</inlineHelpText>
    <label>Enable Debug</label>
    <type>Checkbox</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Enable_Full_Payload_Log__c.field-meta.xml
<CustomField>
    <fullName>Enable_Full_Payload_Log__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Platform Events may include sensitive information. By disabling this checkbox the log will not include the full Platform Event payload. Only the individual fields configured for logging will be available.</description>
    <inlineHelpText>Platform Events may include sensitive information. By disabling this checkbox the log will not include the full Platform Event payload. Only the individual fields configured for logging will be available.</inlineHelpText>
    <label>Enable Full Payload Log</label>
    <type>Checkbox</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Enable_Log_Records__c.field-meta.xml
<CustomField>
    <fullName>Enable_Log_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable or disabled the generation of Platform Event Log records.</description>
    <inlineHelpText>Enable or disabled the generation of Platform Event Log records.</inlineHelpText>
    <label>Enable Log Records</label>
    <type>Checkbox</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Field_Logs__c.field-meta.xml
<CustomField>
    <fullName>Field_Logs__c</fullName>
    <description>Comma separated list of Platform Event Field API names to be logged in Platform Event Field Log object on parent Platform Event Log record</description>
    <inlineHelpText>Comma separated list of Platform Event Field API names to be logged in Platform Event Field Log object on parent Platform Event Log record</inlineHelpText>
    <label>Field Logs</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Completely enable or disable the Platform Event Logging Service for this Platform Event Type</description>
    <inlineHelpText>Completely enable or disable the Platform Event Logging Service for this Platform Event Type</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Platform_Event_Type_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Type_API_Name__c</fullName>
    <description>API Name of Platform Event Type</description>
    <inlineHelpText>API Name of Platform Event Type</inlineHelpText>
    <label>Platform Event Type API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Publishing_User_Field__c.field-meta.xml
<CustomField>
    <fullName>Publishing_User_Field__c</fullName>
    <description>Field path used to pull user id to set as the Platform_Event_Log__c.Publishing_User__c field. Defaults to CreatedById if not populated.</description>
    <inlineHelpText>Field path used to pull user id to set as the Platform_Event_Log__c.Publishing_User__c field. Defaults to CreatedById if not populated.</inlineHelpText>
    <label>Publishing User Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/lpes_CustomMetadataConfigurationTest.cls
@isTest public class lpes_CustomMetadataConfigurationTest {
    
    private static final integer count;
    private static list<Platform_Event_Log_Configuration__mdt> eventConfigurations;
    private static exception logException;
    private static lpes_CustomMetadataConfiguration config;
    private static string eventType;

    static 
    {
        count = 250;
        eventType = 'LogPlatformEventsServiceTestEvent__e';
        eventConfigurations = new List<Platform_Event_Log_Configuration__mdt>();
    }


    /** PRIVATE HELPER METHODS **/


    /* 
    * Leveraging the JSON.deserialize() method allows us to work 
    * around "Field Not Writable" limitations for mock data
    */

    private static void createPlatformEventConfigurationRecords(integer count, string fieldsList)
    {
        for (integer i=0;i<count;i++) 
        {
            eventConfigurations.add((Platform_Event_Log_Configuration__mdt)JSON.deserialize('{' +
                '"DeveloperName":"EVENT LOG CONFIG '+i+'",' +
                '"MasterLabel":"EVENT LOG CONFIG '+i+'",' +
                '"Is_Active__c":true,' +
                '"Enable_Debug__c":true,' +
                '"Enable_Log_Records__c":true,' +
                '"Enable_Full_Payload_Log__c":true,' +
                '"Publishing_User_Field__c":"JsonTextField__c.Publishing_User__c",' +
                '"Field_Logs__c":"'+fieldsList+'",' +
                '"Platform_Event_Type_API_Name__c":"'+eventType+'"' +
                '}',
                Platform_Event_Log_Configuration__mdt.class));
        }
    }    

    public static list<Platform_Event_Log_Configuration__mdt> getEventConfigurations()
    {
        return eventConfigurations;
    }


    // All tests are running the same core functionality, just with different config and events
    // Pulled this out to avoid duplication across all tests
    private static void doTest()
    {
        try {
            config = new lpes_CustomMetadataConfiguration(eventType);
        } catch (exception e) {
            logException = e;
            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());
        }
    }

    private static void assertDefaultGetResponses()
    {
        System.assertEquals(null, config);
    }

    private static void assertValidConfigurationGetResponses()
    {
        System.assert(config.getIsDebug());
        System.assert(config.getIsLogFullPayload());
        System.assert(config.getIsLogRecords());
        System.assertEquals('JsonTextField__c.Publishing_User__c',config.getPublishingUserField());
        System.assertEquals('{1} - {0}',config.getNameFormatPlaceholder());
        System.assertEquals(new list<string>{'JsonTextField__c'}, config.getFieldsToLog());
    }
    



    /** TEST METHODS **/

    @isTest static void noConfigurations() 
    { 
        test.startTest();
        doTest();
        test.stopTest();

        System.assert(logException!=null);
        System.assert(logException.getMessage().contains(lpes_CustomMetadataConfiguration.NO_EVENT_CONFIGURATIONS_MESSAGE.split(':')[0]));
        assertDefaultGetResponses();
    }

    @isTest static void multipleActiveConfigurations() 
    {
        createPlatformEventConfigurationRecords(3,'JsonTextField__c');

        test.startTest();
        doTest();
        test.stopTest();

        System.assert(logException!=null);
        System.assert(logException.getMessage().contains(lpes_CustomMetadataConfiguration.DUPLICATE_EVENT_CONFIGURATIONS_MESSAGE.split(':')[0]));
        assertDefaultGetResponses();
    }

    @isTest static void activeAndInactiveConfigurationsPassing() 
    {
        createPlatformEventConfigurationRecords(3,'JsonTextField__c');
        eventConfigurations[0].is_active__c=false;
        eventConfigurations[2].is_active__c=false;

        test.startTest();
        doTest();
        test.stopTest();

        System.assert(logException==null);
        assertValidConfigurationGetResponses();
    }

    @isTest static void activeAndInactiveConfigurationsFailing() 
    {
        createPlatformEventConfigurationRecords(3,'JsonTextField__c');
        eventConfigurations[0].is_active__c=false;

        test.startTest();
        doTest();
        test.stopTest();

        System.assert(logException!=null);
        System.assert(logException.getMessage().contains(lpes_CustomMetadataConfiguration.DUPLICATE_EVENT_CONFIGURATIONS_MESSAGE.split(':')[0]));
        assertDefaultGetResponses();
    }


}