force-app/main/default/objects/Platform_Event_Log__c/Platform_Event_Log__c.object-meta.xml
<CustomObject>
    <description>A log of all platform events consumed while trigger for that type is enabled.</description>
    <label>Platform Event Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log__c/fields/Platform_Event_Payload__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Payload__c</fullName>
    <description>The full content of the platform event that is logged</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The full content of the platform event that is logged</inlineHelpText>
    <label>Platform Event Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log__c/fields/Platform_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Type__c</fullName>
    <description>API name of the Platform Event type</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>API name of the Platform Event type</inlineHelpText>
    <label>Platform Event Type</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log__c/fields/Publishing_User__c.field-meta.xml
<CustomField>
    <fullName>Publishing_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who published the Platform Event. Is populated by CreatedById by default, but can configure a populating field in the custom metadata configuration.</description>
    <inlineHelpText>User who published the Platform Event. Is populated by CreatedById by default, but can configure a populating field in the custom metadata configuration.</inlineHelpText>
    <label>Publishing User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Platform_Event_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log__c/fields/ReplayId__c.field-meta.xml
<CustomField>
    <fullName>ReplayId__c</fullName>
    <label>ReplayId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/Platform_Event_Log_Field__c.object-meta.xml
<CustomObject>
    <description>Individual field values for a platform event log for easier readability and reporting</description>
    <label>Platform Event Log Field</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Log Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>Name of the field being captured</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the field being captured</inlineHelpText>
    <label>Field Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <description>Value of the Platform Event Field</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value of the Platform Event Field</inlineHelpText>
    <label>Field Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Platform_Event_Log__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Log__c</fullName>
    <label>Platform Event Log</label>
    <referenceTo>Platform_Event_Log__c</referenceTo>
    <relationshipLabel>Platform Event Log Fields</relationshipLabel>
    <relationshipName>Platform_Event_Log_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/lpes_PlatformEventLogFactory.cls
public inherited sharing class lpes_PlatformEventLogFactory
{

    private sobject[] newlist;
    private final lpes_ILogPlatformEventsConfiguration config;
    private map<string,list<platform_event_log_field__c>> replayidToFieldLogs;
    private map<string,platform_event_log__c> logs;
    private list<platform_event_log_field__c> fieldlogs;
    private map<sobjecttype,string> typeToName;
    private id publishingUser;
    protected map<string,fieldsetting> fieldPathToSettings;

    public lpes_PlatformEventLogFactory(lpes_ILogPlatformEventsConfiguration config)
    {
        if (config==null)
            throw new PlatformEventLogFactoryException(lpes_ExceptionMessageWrapper.INVALID_PARAMETERS_MESSAGE);

        this.config = config;
    }


    public lpes_PlatformEventLogWrapper buildLogs(list<sobject> events)
    {
        if (events==null)
            throw new PlatformEventLogFactoryException(lpes_ExceptionMessageWrapper.INVALID_PARAMETERS_MESSAGE);

        this.newlist = events;
        this.logs = new map<string,platform_event_log__c>();
        this.replayidToFieldLogs = new map<string,list<platform_event_log_field__c>>();
        this.fieldPathToSettings = new map<string,fieldsetting>();
        this.typeToName = new map<sobjecttype,string>();

        // populate fielPathToSettings map 
        this.setLogFields(this.config.getFieldsToLog());
        this.setPublishingUserField(this.config.getPublishingUserField());


        // build platform_event_log and platform_event_log_field records
        for (SObject event : this.newlist)
        {
            string platformEventType = this.getPlatformEventTypeName(event.getSObjectType());
            platform_event_log_field__c[] fields = this.buildLogFieldsList(event,platformEventType);

            // Add Platform Event Log record to list
            this.logs.put((string) event.get('replayid'), new platform_event_log__c(
                name = String.format(this.config.getNameFormatPlaceholder(),
                                     new list<string>{(string)event.get('replayid'),platformEventType}),
                replayid__c = (string)event.get('replayid'),                
                platform_event_type__c = platformEventType,
                publishing_user__c = (id)publishingUser,
                platform_event_payload__c = this.config.getIsLogFullPayload() ? 
                                            JSON.serialize(event) : lpes_ExceptionMessageWrapper.DISABLED_PAYLOAD_LOG_MESSSAGE
            ));

            this.replayidToFieldLogs.put((string)event.get('replayid'),fields);

            // reset tmp fields
            this.publishingUser = null;
        }

        return new lpes_PlatformEventLogWrapper(this.logs, this.replayidToFieldLogs);
    }

    private list<platform_event_log_field__c> buildLogFieldsList(SObject event, String platformEventType)
    {
        list<platform_event_log_field__c> fields = new list<platform_event_log_field__c>();
        // iterate through all fields to log
        for (FieldSetting fs : fieldPathToSettings.values())
        {
            string value = this.getFieldValue(event,fs.fieldPath,platformEventType);

            // allow admin to configure what field to use to populate publishing_user__c
            if (fs.isPublishingUserField)
                this.publishingUser = this.getUserId(value);

            if (fs.isLogField)
                fields.add(new platform_event_log_field__c(
                    name = fs.fieldPath+' - '+event.get('replayid'),
                    field_name__c = fs.fieldPath,
                    field_value__c = value
                ));
        }

        return fields;
    }


    // Iterate through all fields in field path and retrieve value
    private string getFieldValue(sobject event, string field, string platformEventType)
    {
        String value; 
        map<string,object> nestedObj;

        // support dot notation for valid json text fields on the platform event
        // iterate through fields in field path to get final value
        for (string attribute : field.split('\\.'))
        {
            try {
                // fields in json object stored in the platform event field
                if (nestedObj!=null)
                {
                    value = String.valueOf(nestedObj.get(attribute));
                    if (nestedObj.get(attribute)==null || nestedObj.get(attribute) instanceof map<string,object>)
                        nestedObj = (map<string,object>)nestedObj.get(attribute);
                }

                // platform event field (first field in each field path)
                else
                {
                    try {
                        value =  String.valueOf(event.get(attribute));
                    } catch(SObjectException e) {
                        System.debug(e.getMessage());
                        System.debug(lpes_ExceptionMessageWrapper.INVALID_EVENT_FIELD_MESSAGE);
                        value = String.format(lpes_ExceptionMessageWrapper.INVALID_EVENT_FIELD_MESSAGE, new list<string>{field,platformEventType});
                        break;
                    }
                    
                    // Only parse nestedObj for fields using dot notation
                    if (field.contains('.'))
                        nestedObj = (map<string,object>)JSON.deserializeUntyped(value);
                }
            } catch(exception e) {
                System.debug(e.getMessage());
                System.debug(lpes_ExceptionMessageWrapper.JSON_PARSE_ERROR_MESSAGE);
                value = lpes_ExceptionMessageWrapper.JSON_PARSE_ERROR_MESSAGE;
                break;
            }

            // if part way through field path and no value is returned, break loop
            if (nestedObj==null)
                break;
        }

        return value;
    }


    // Validate id string and return valid id or null
    private id getUserId(string idstring)
    {
        try {
            return ((id)idstring).getSobjectType().getDescribe().getName()=='User' ? idstring : null;
        } catch (exception e) {
            System.debug('Invalid User Id Value');
            System.debug(e.getMessage());
            return null;
        }
    }

    private string getPlatformEventTypeName(sobjecttype eventType) 
    {
        String name = typeToName.get(eventType);
        if (name==null)
        {
            name = eventType.getDescribe().getName();
            typeToName.put(eventType,name);
        }

        return name;
    }



    /******************************************************
         FIELD SETTING INNER CLASS AND HELPER METHODS
    *******************************************************/


    private class FieldSetting
    {
        private final string fieldPath;
        private boolean isPublishingUserField = false;
        private boolean isLogField = false;

        private FieldSetting(string fieldPath)
        {
            this.fieldPath = fieldPath;
        }

        private void setLogField()
        {
            this.isLogField=true;
        }

        private void setPublishingUserField()
        {
            this.isPublishingUserField=true;
        }
    }

    private void setPublishingUserField(string fieldPath)
    {
        if (String.isBlank(fieldPath))
            fieldPath = 'CreatedById';

        FieldSetting fieldSetting = getFieldSetting(fieldPath);
        fieldSetting.setPublishingUserField();
        this.fieldPathToSettings.put(fieldPath,fieldSetting);
    }

    private void setLogFields(list<string> fieldsToLog)
    {
        for (string fieldPath : fieldsToLog)
        {
            if (!String.isBlank(fieldPath))
                this.setLogField(fieldPath);
        }
    }

    private void setLogField(string fieldPath)
    {
        if (String.isBlank(fieldPath))
            return;

        FieldSetting fieldSetting = getFieldSetting(fieldPath);
        fieldSetting.setLogField();
        this.fieldPathToSettings.put(fieldPath,fieldSetting);
    }

    private FieldSetting getFieldSetting(string fieldPath)
    {
        return this.fieldPathToSettings.get(fieldPath)!=null ? this.fieldPathToSettings.get(fieldPath) : new FieldSetting(fieldPath);
    }



    public class PlatformEventLogFactoryException extends Exception {}
}