force-app/main/default/objects/Platform_Event_Log__c/Platform_Event_Log__c.object-meta.xml
<CustomObject>
    <description>A log of all platform events consumed while trigger for that type is enabled.</description>
    <label>Platform Event Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Field__c/Platform_Event_Log_Field__c.object-meta.xml
<CustomObject>
    <description>Individual field values for a platform event log for easier readability and reporting</description>
    <label>Platform Event Log Field</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Log Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Platform_Event_Log__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Log__c</fullName>
    <label>Platform Event Log</label>
    <referenceTo>Platform_Event_Log__c</referenceTo>
    <relationshipLabel>Platform Event Log Fields</relationshipLabel>
    <relationshipName>Platform_Event_Log_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/lpes_PlatformEventLogWrapper.cls
public inherited sharing class lpes_PlatformEventLogWrapper 
{
    
    public set<string> replayIds {get; private set;}
    public map<string,platform_event_log__c> platformEventLogs {get; private set;}
    public map<string,list<platform_event_log_field__c>> platformEventLogFields {get; private set;}

    public lpes_PlatformEventLogWrapper(map<string,platform_event_log__c> logs, map<string,list<platform_event_log_field__c>> fields) 
    {
        if (logs==null || fields==null)
            throw new PlatformEventLogWrapperException(lpes_ExceptionMessageWrapper.INVALID_PARAMETERS_MESSAGE);

        this.replayIds = logs.keyset();
        this.platformEventLogs = logs;
        this.platformEventLogFields = fields;
    }


    public class PlatformEventLogWrapperException extends Exception {}
}