force-app/main/default/objects/Platform_Event_Log__c/Platform_Event_Log__c.object-meta.xml
<CustomObject>
    <description>A log of all platform events consumed while trigger for that type is enabled.</description>
    <label>Platform Event Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Field__c/Platform_Event_Log_Field__c.object-meta.xml
<CustomObject>
    <description>Individual field values for a platform event log for easier readability and reporting</description>
    <label>Platform Event Log Field</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Log Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Platform_Event_Log__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Log__c</fullName>
    <label>Platform Event Log</label>
    <referenceTo>Platform_Event_Log__c</referenceTo>
    <relationshipLabel>Platform Event Log Fields</relationshipLabel>
    <relationshipName>Platform_Event_Log_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/lpes_PlatformEventLogWrapperTest.cls
@istest public class lpes_PlatformEventLogWrapperTest {

    private static integer count = 20;
    private static integer fieldCount = 5;

    private static lpes_PlatformEventLogWrapper logWrapper;
    private static map<string,platform_event_log__c> logs;
    private static map<string,list<platform_event_log_field__c>> fieldLogs; 


    /***************************************************
                   PRIVATE HELPER METHODS
    ****************************************************/

    private static void doUnitTest()
    {
        logWrapper = new lpes_PlatformEventLogWrapper(logs,fieldLogs);
    }



    /***************************************************
                        UNIT TESTS
    ****************************************************/

    @istest public static void populateValuesAndRetrieveThem()
    {
        logs = lpes_TestDataFactory.generateLogMapForWrapper(count);
        fieldLogs = lpes_TestDataFactory.generateFieldLogMapForWrapper(count,fieldCount);

        test.startTest();
        doUnitTest();
        test.stopTest();

        System.assertEquals(logs,logWrapper.platformEventLogs);
        System.assertEquals(logs.keyset(),logWrapper.replayIds);
        System.assertEquals(fieldLogs,logWrapper.platformEventLogFields);
    }


    @istest public static void passEmptyVariablesToConstructor()
    {
        logs = new map<string,platform_event_log__c>();
        fieldLogs = new map<string,list<platform_event_log_field__c>>();

        test.startTest();
        doUnitTest();
        test.stopTest();

        System.assertEquals(logs,logWrapper.platformEventLogs);
        System.assertEquals(logs.keyset(),logWrapper.replayIds);
        System.assertEquals(fieldLogs,logWrapper.platformEventLogFields);
    }


    @istest public static void passNullToConstructor()
    {
        Exception wrapperException;

        test.startTest();
        try {
            doUnitTest();
        } catch (exception e) {
            System.debug(e);
            System.debug(e.getMessage());
            wrapperException = e;
        }
        test.stopTest();

        System.assertNotEquals(null,wrapperException);
        System.assertEquals(lpes_ExceptionMessageWrapper.INVALID_PARAMETERS_MESSAGE,wrapperException.getMessage());
    }
}