force-app/main/default/objects/Platform_Event_Log__c/Platform_Event_Log__c.object-meta.xml
<CustomObject>
    <description>A log of all platform events consumed while trigger for that type is enabled.</description>
    <label>Platform Event Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log__c/fields/Publishing_User__c.field-meta.xml
<CustomField>
    <fullName>Publishing_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who published the Platform Event. Is populated by CreatedById by default, but can configure a populating field in the custom metadata configuration.</description>
    <inlineHelpText>User who published the Platform Event. Is populated by CreatedById by default, but can configure a populating field in the custom metadata configuration.</inlineHelpText>
    <label>Publishing User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Platform_Event_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/Platform_Event_Log_Field__c.object-meta.xml
<CustomObject>
    <description>Individual field values for a platform event log for easier readability and reporting</description>
    <label>Platform Event Log Field</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Log Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>Name of the field being captured</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the field being captured</inlineHelpText>
    <label>Field Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <description>Value of the Platform Event Field</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value of the Platform Event Field</inlineHelpText>
    <label>Field Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Platform_Event_Log__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Log__c</fullName>
    <label>Platform Event Log</label>
    <referenceTo>Platform_Event_Log__c</referenceTo>
    <relationshipLabel>Platform Event Log Fields</relationshipLabel>
    <relationshipName>Platform_Event_Log_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/lpes_SObjectPlatformEventLoggerTest.cls
@istest public class lpes_SObjectPlatformEventLoggerTest {

    private static List<platform_event_log__c> insertedLogs; // Logs stored here if PerformDML is FALSE
    private static List<platform_event_log_field__c> insertedFieldLogs; // Logs stored here if PerformDML is FALSE
    
    private static lpes_PlatformEventLogWrapper logContainer;
    private static boolean performDML;
    private static boolean isDebug;
    private static boolean isLogRecords;

    static 
    {
        performDML = false;
        isLogRecords = true;
        isDebug = true;
        insertedLogs = new List<platform_event_log__c>();
        insertedFieldLogs = new List<platform_event_log_field__c>();
    }


    /***************************************************
                   PUBLIC GETTER METHODS
    ****************************************************/
    
    public static boolean getPerformDML()
    {
        return performDML;
    }

    public static void setInsertedLogs(List<platform_event_log__c> logs)
    {
        insertedLogs = logs;
    }

    public static void setInsertedLogFields(List<platform_event_log_field__c> fieldLogs)
    {
        insertedFieldLogs = fieldLogs;
    }



    /***************************************************
                   PRIVATE HELPER METHODS
    ****************************************************/ 

    private static list<platform_event_log__c> getInsertedLogs() 
    {
        if (performDML)
            return [select id, name, publishing_user__c from platform_event_log__c];
        else 
            return insertedLogs;
    }

    private static list<platform_event_log_field__c> getInsertedFieldLogs()
    {
        if (performDML)
            return [select id, field_name__c, field_value__c from platform_event_log_field__c];
        else 
            return insertedFieldLogs;
    }

    private static void doUnitTest()
    {
        new lpes_SObjectPlatformEventLogger(isLogRecords,isDebug).logEvents(logContainer);
    }


    /***************************************************
                        UNIT TESTS
    ****************************************************/


    @istest static void passEmptyMapsToLogWrapperAndLogger() 
    {
        logContainer = new lpes_PlatformEventLogWrapper(new map<string,platform_event_log__c>(), new map<string,list<platform_event_log_field__c>>());
        test.startTest();
        doUnitTest();
        test.stopTest();

        System.assertEquals(0,getInsertedLogs().size());
        System.assertEquals(0,getInsertedFieldLogs().size());
    }

    @istest static void passPopulatedLogWrapperToLogger()
    {
        integer logCount = 20;
        integer fieldLogCount = 5;
        logContainer = new lpes_PlatformEventLogWrapper(
            lpes_TestDataFactory.generateLogMapForWrapper(logCount),
            lpes_TestDataFactory.generateFieldLogMapForWrapper(logCount,fieldLogCount)
        );

        test.startTest();
        doUnitTest();
        test.stopTest();

        System.assertEquals(logCount,getInsertedLogs().size());
        System.assertEquals(logCount*fieldLogCount,getInsertedFieldLogs().size());
    }

    /***************************************************
                    INTEGRATION TESTS
    ****************************************************/

    @isTest static void performDmlInBulk() 
    {
        // PERFORM INSERTS
        integer logCount = 250; // test valid config with high count
        integer fieldLogCount = 5;
        performDML = true; 
        
        logContainer = new lpes_PlatformEventLogWrapper(
            lpes_TestDataFactory.generateLogMapForWrapper(logCount),
            lpes_TestDataFactory.generateFieldLogMapForWrapper(logCount,fieldLogCount)
        );

        test.startTest();
        doUnitTest();
        test.stopTest();

        System.assertEquals(logCount,getInsertedLogs().size());
        System.assertEquals(logCount*fieldLogCount,getInsertedFieldLogs().size());
    }
}