force-app/main/default/objects/Platform_Event_Log__c/Platform_Event_Log__c.object-meta.xml
<CustomObject>
    <description>A log of all platform events consumed while trigger for that type is enabled.</description>
    <label>Platform Event Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log__c/fields/Platform_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Type__c</fullName>
    <description>API name of the Platform Event type</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>API name of the Platform Event type</inlineHelpText>
    <label>Platform Event Type</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log__c/fields/ReplayId__c.field-meta.xml
<CustomField>
    <fullName>ReplayId__c</fullName>
    <label>ReplayId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/Platform_Event_Log_Field__c.object-meta.xml
<CustomObject>
    <description>Individual field values for a platform event log for easier readability and reporting</description>
    <label>Platform Event Log Field</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Platform Event Log Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Event Log Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>Name of the field being captured</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the field being captured</inlineHelpText>
    <label>Field Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <description>Value of the Platform Event Field</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value of the Platform Event Field</inlineHelpText>
    <label>Field Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Field__c/fields/Platform_Event_Log__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Log__c</fullName>
    <label>Platform Event Log</label>
    <referenceTo>Platform_Event_Log__c</referenceTo>
    <relationshipLabel>Platform Event Log Fields</relationshipLabel>
    <relationshipName>Platform_Event_Log_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/lpes_TestDataFactory.cls
@istest public class lpes_TestDataFactory {

    public static map<string,platform_event_log__c> generateLogMapForWrapper(integer count)
    {
        map<string,platform_event_log__c> tmpLogs = new map<string,platform_event_log__c>();
        
        for (integer i=0;i<count;i++)
        {
            tmpLogs.put('12345'+i, new platform_event_log__c(
                replayid__c='12345'+i,
                platform_event_type__c='test_event__e'
            ));
        }

        return tmpLogs;
    }

    public static map<string,list<platform_event_log_field__c>> generateFieldLogMapForWrapper(integer count, integer fieldCount)
    {
        map<string,list<platform_event_log_field__c>> tmpLogs = new map<string,list<platform_event_log_field__c>>();
        
        for (integer i=0;i<count;i++)
        {
            list<platform_event_log_field__c> tmpFields = new list<platform_event_log_field__c>();
            for (integer j=0;j<fieldCount;j++)
                tmpFields.add( new platform_event_log_field__c(
                    field_name__c='name_'+j,
                    field_value__c='value_'+j
                ));
            tmpLogs.put('12345'+i, tmpFields);
        }

        return tmpLogs;
    }
}