examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/Platform_Event_Log_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Manage the configuration for Platform Event Logging Service for multiple Platform Event types.</description>
    <label>Platform Event Log Configuration</label>
    <pluralLabel>Platorm Event Log Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Enable_Debug__c.field-meta.xml
<CustomField>
    <fullName>Enable_Debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Provide debugging in the Apex logs.</description>
    <inlineHelpText>Provide debugging in the Apex logs.</inlineHelpText>
    <label>Enable Debug</label>
    <type>Checkbox</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Enable_Full_Payload_Log__c.field-meta.xml
<CustomField>
    <fullName>Enable_Full_Payload_Log__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Platform Events may include sensitive information. By disabling this checkbox the log will not include the full Platform Event payload. Only the individual fields configured for logging will be available.</description>
    <inlineHelpText>Platform Events may include sensitive information. By disabling this checkbox the log will not include the full Platform Event payload. Only the individual fields configured for logging will be available.</inlineHelpText>
    <label>Enable Full Payload Log</label>
    <type>Checkbox</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Enable_Log_Records__c.field-meta.xml
<CustomField>
    <fullName>Enable_Log_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable or disabled the generation of Platform Event Log records.</description>
    <inlineHelpText>Enable or disabled the generation of Platform Event Log records.</inlineHelpText>
    <label>Enable Log Records</label>
    <type>Checkbox</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Field_Logs__c.field-meta.xml
<CustomField>
    <fullName>Field_Logs__c</fullName>
    <description>Comma separated list of Platform Event Field API names to be logged in Platform Event Field Log object on parent Platform Event Log record</description>
    <inlineHelpText>Comma separated list of Platform Event Field API names to be logged in Platform Event Field Log object on parent Platform Event Log record</inlineHelpText>
    <label>Field Logs</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Completely enable or disable the Platform Event Logging Service for this Platform Event Type</description>
    <inlineHelpText>Completely enable or disable the Platform Event Logging Service for this Platform Event Type</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Platform_Event_Type_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Type_API_Name__c</fullName>
    <description>API Name of Platform Event Type</description>
    <inlineHelpText>API Name of Platform Event Type</inlineHelpText>
    <label>Platform Event Type API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

examples/CustomMetadataBasedConfiguration/main/default/objects/Platform_Event_Log_Configuration__mdt/fields/Publishing_User_Field__c.field-meta.xml
<CustomField>
    <fullName>Publishing_User_Field__c</fullName>
    <description>Field path used to pull user id to set as the Platform_Event_Log__c.Publishing_User__c field. Defaults to CreatedById if not populated.</description>
    <inlineHelpText>Field path used to pull user id to set as the Platform_Event_Log__c.Publishing_User__c field. Defaults to CreatedById if not populated.</inlineHelpText>
    <label>Publishing User Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/lpes_CustomMetadataConfiguration.cls
public with sharing class lpes_CustomMetadataConfiguration implements lpes_ILogPlatformEventsConfiguration 
{

    private boolean isLogRecords = false;
    private boolean isDebug = false;
    private boolean isLogFullPayload = false;
    private string publishingUserField = '';
    private list<string> fieldsToLog = new list<string>();
    private string nameFormatPlaceholder = '';

    private final platform_event_log_configuration__mdt config;
    private final string platformEventType;

    @testvisible private static final string DUPLICATE_EVENT_CONFIGURATIONS_MESSAGE;
    @testvisible private static final string NO_EVENT_CONFIGURATIONS_MESSAGE;

    static 
    {
        DUPLICATE_EVENT_CONFIGURATIONS_MESSAGE = 'DUPLICATE_PLATFORM_EVENT_CONFIGURATIONS: '+Label.lpes_duplicate_event_configurations_message;
        NO_EVENT_CONFIGURATIONS_MESSAGE = 'NO_PLATFORM_EVENT_CONFIGURATIONS: '+Label.lpes_no_event_configurations_message;
    }

    public lpes_CustomMetadataConfiguration(string platformEventType) {

        this.platformEventType = platformEventType;
        platform_event_log_configuration__mdt[] eventLogConfigurations =
                                    [
                                        select masterlabel,
                                        is_active__c,
                                        enable_debug__c,
                                        enable_log_records__c,
                                        enable_full_payload_log__c,
                                        field_logs__c,
                                        publishing_user_field__c,
                                        Platform_Event_Type_API_Name__c
                                        from platform_event_log_configuration__mdt
                                        where Platform_Event_Type_API_Name__c=:platformEventType
                                    ];

        // Use mocks if running test
        if (test.isRunningTest())
            eventLogConfigurations = lpes_CustomMetadataConfigurationTest.getEventConfigurations();



        // At least one configuration is required, otherwise throw exception to alert admin
        if (eventLogConfigurations.size()==0)
            throw new lpes_CustomMetadataConfigurationException(String.format(NO_EVENT_CONFIGURATIONS_MESSAGE,new list<string>{platformEventType}));

        // Multiple *active* configurations also throw exception to alert admin.
        // No exception is thrown if all are inactive.
        // In this case we assume they have been intentionally disabled.
        integer activeConfigurations = 0;
        for (platform_event_log_configuration__mdt eventConfig : eventLogConfigurations)
        {
            if (eventConfig.is_active__c)
            {
                activeConfigurations+=1;
                if (activeConfigurations>1)
                    throw new lpes_CustomMetadataConfigurationException(String.format(DUPLICATE_EVENT_CONFIGURATIONS_MESSAGE,new list<string>{platformEventType}));

                this.config = eventConfig;
            }
        }

        if (this.config!=null)
        {
            this.isDebug = this.config.enable_debug__c;
            this.isLogRecords = this.config.enable_log_records__c;
            this.isLogFullPayload = this.config.enable_full_payload_log__c;
            this.publishingUserField = this.config.publishing_user_field__c;
            this.fieldsToLog = this.config.field_logs__c.split(',');
        }
        this.nameFormatPlaceholder = this.platformEventType + ' - {0}';
    }

    public boolean getIsDebug()
    {
        return this.isDebug;
    }

    public boolean getIsLogRecords()
    {
        return this.isLogRecords;
    }

    public boolean getIsLogFullPayload()
    {
        return this.isLogFullPayload;
    }

    public string getPublishingUserField()
    {
        return this.publishingUserField;
    }

    public list<string> getFieldsToLog()
    {
        return this.fieldsToLog;
    }

    // {0} replaced by ReplayId
    public string getNameFormatPlaceholder()
    {
        return this.nameFormatPlaceholder;
    }

    public class lpes_CustomMetadataConfigurationException extends Exception {}
}